services:
  hypha-core-db:
    image: postgres:14.3-alpine
    container_name: hypha-core-db
    ports:
      - "6433:5432"
    environment:
      POSTGRES_USER: ${HYPHA_CORE_DB_USERNAME}
      POSTGRES_PASSWORD: ${HYPHA_CORE_DB_PASSWORD}
      POSTGRES_DB: coredb
    volumes:
      - ./pg_core/data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || pg_isready"
      interval: 5s
      timeout: 2s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
  hypha-core:
    image: "mycesys/hypha-core:${HYPHA_CORE_VERSION}"
    container_name: hypha-core
    restart: on-failure
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: ${HYPHA_CORE_LIMIT_MAX_RAM}
        reservations:
          memory: ${HYPHA_CORE_LIMIT_MAX_RAM}
    volumes:
      - ./core/common/avatars:/server/data/avatars
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://hypha-core-db:5432/coredb
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hypha-core-db:5432/coredb
      - AVATAR_ROOT_DIR=/server/data/avatars
    env_file:
      - ./.env
    depends_on:
      hypha-core-db:
        condition: service_healthy
      vault:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
