services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.10.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    env_file:
      - ./.env
