services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
    volumes:
      - ./consul_config:/consul_config
    command: sh /consul_config/start-consul.sh
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    env_file:
      - ./.env
