services:
  hypha-backend-dictionary:
    image: "mycesys/hypha-backend-dictionary:${HYPHA_BACKEND_DICTIONARY_VERSION}"
    container_name: hypha-backend-dictionary
    restart: on-failure
    ports:
      - "8090:8090"
    healthcheck:
      test: curl -s http://localhost:8090/actuator/health| grep UP || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
