mkdir -p auth/user/avatars/
mkdir -p core/common/avatars/
mkdir -p files/data/
mkdir -p oauth/keys/
mkdir -p ssh/keys/
mkdir -p ssl
mkdir -p pg_auth
mkdir -p pg_core
mkdir -p pg_dashboard
mkdir -p pg_fm
mkdir -p pg_rm
mkdir -p pg_tm
mkdir -p pg_workflow
mkdir -p rabbitmq_data
mkdir -p vault_data
