services:
  hypha-gateway:
    image: "mycesys/hypha-gateway:${HYPHA_GATEWAY_VERSION}"
    container_name: hypha-gateway
    restart: on-failure
    ports:
      - "8091:8091"
    healthcheck:
      test: curl -s http://localhost:8091/actuator/health| grep UP || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: ${HYPHA_APP_GW_LIMIT_MAX_RAM}
        reservations:
          memory: ${HYPHA_APP_GW_LIMIT_MAX_RAM}
    volumes:
      - ${PWD}/ssl:/ssl
    env_file:
      - ./.env
    depends_on:
      consul:
        condition: service_started
      vault:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
