services:
  hypha-gateway:
    image: "mycesys/hypha-gateway:${HYPHA_GATEWAY_VERSION}"
    container_name: hypha-gateway
    restart: on-failure
    ports:
      - "8091:8091"
    deploy:
      resources:
        limits:
          memory: ${HYPHA_APP_GW_LIMIT_MAX_RAM}
        reservations:
          memory: ${HYPHA_APP_GW_LIMIT_MAX_RAM}
    volumes:
      - ${PWD}/ssl:/ssl
    env_file:
      - ./.env
    depends_on:
      vault:
        condition: service_healthy
