services:
  hub-ui:
    container_name: hub-ui
    image: "mycesys/hub-ui:${HUB_UI_VERSION}"
    ports:
      - '${HUB_PUBLIC_PORT}:3001'
    volumes:
      #- /etc/letsencrypt_shared:/etc/letsencrypt
      - ${PWD}/ssl_cert.conf:/etc/nginx/ssl_cert.conf
      - ${PWD}/ssl:/etc/ssl
    restart: always
    environment:
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_PORT: ${CONSUL_PORT}
    env_file:
      - ./.env
    depends_on:
      - hub-auth
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
